const demoUsers = [
  {
    username: 'admin',
    first_name: 'Admin',
    last_name: 'User',
    gender: 'male',
    birth_date: new Date('1990-01-15'),
    role: 'admin',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'john.doe',
    first_name: 'John',
    last_name: 'Doe',
    gender: 'male',
    birth_date: new Date('1985-05-20'),
    role: 'user',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'jane.smith',
    first_name: 'Jane',
    last_name: 'Smith',
    gender: 'female',
    birth_date: new Date('1992-08-10'),
    role: 'user',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'alex.johnson',
    first_name: 'Alex',
    last_name: 'Johnson',
    gender: 'other',
    birth_date: new Date('1988-03-25'),
    role: 'user',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'maria.garcia',
    first_name: 'Maria',
    last_name: 'Garcia',
    gender: 'female',
    birth_date: new Date('1995-11-30'),
    role: 'user',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'Hokage',
    first_name: 'Naruto',
    last_name: 'Uzumaki',
    gender: 'male',
    birth_date: new Date('2000-11-30'),
    role: 'admin',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'Sharingan',
    first_name: 'Sasuke',
    last_name: 'Uchiha',
    gender: 'male',
    birth_date: new Date('2000-11-30'),
    role: 'admin',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    username: 'Shadow',
    first_name: 'John',
    last_name: 'Smith',
    gender: 'male',
    birth_date: new Date('2002-11-30'),
    role: 'user',
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = demoUsers;
